language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean build -i --continue


after_success:
  - bash <(curl -s https://codecov.io/bash)

  - docker --version
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - export PATH=$PATH:$HOME/.local/bin

  # TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`

  # SILVERSTRIPE CLIENT
  - export CONFIG=peavers/silverstripe-client
  - docker build -t $CONFIG ./silverstripe-client
  - docker tag $CONFIG:$TAG $CONFIG:$TAG
  - docker push $CONFIG:$TAG

  # SILVERSTRIPE SERVICE
  - export CONFIG=peavers/silverstripe-client
  - docker build -t $CONFIG ./silverstripe-service
  - docker tag $CONFIG:$TAG $CONFIG:$TAG
  - docker push $CONFIG:$TAG
